[package]
name = "codotaku-math-expression-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chumsky = { git = "https://github.com/zesterer/chumsky", version = "1.0.0-alpha.6", features = ["nightly"] }
num-traits = "0.2.18"
thiserror = "1.0.58"
